# networks:
#   app-tier:
#     driver: bridge

services:
  kafka:
    hostname: kafka-dev
    image: mirror.gcr.io/bitnami/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  postgres:
    hostname: pg-dev
    image: mirror.gcr.io/postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=bibaboba